// Generated by CoffeeScript 1.4.0
(function() {

  require(['handlebars', 'underscore', 'Shared', 'jquery', 'bootstrap'], function(Handlebars, _, Shared) {
    return Shared.ApiMakeRequest('events/last.php', {}, function(result) {
      var startDate, str;
      if (!(result.error != null)) {
        startDate = Shared.fullDate(result.starts_at);
        str = 'Le prochain évènement aura lieu le ' + startDate + '. Il s\'intitule <em>' + result.title + '</em>.';
        str += '<p><a class="btn btn-primary btn-large">En savoir plus &raquo;</a></p>';
        return $('.hero-unit .content').html(str);
      }
    });
  });

}).call(this);
