// Generated by CoffeeScript 1.4.0
(function() {

  define(['handlebars', 'underscore', 'jquery'], function(Handlebars, _) {
    var Shared;
    Shared = (function() {

      function Shared() {}

      Shared.prototype.ApiMakeRequest = function(url, params, success, fail, method) {
        if (params == null) {
          params = {};
        }
        if (success == null) {
          success = null;
        }
        if (fail == null) {
          fail = null;
        }
        if (method == null) {
          method = 'GET';
        }
        if (!(success != null)) {
          success = function() {};
        }
        if (!(fail != null)) {
          fail = function() {};
        }
        url = '/ajax/scripts/' + url;
        return $.ajax({
          url: url,
          data: params,
          dataType: 'json',
          success: function(result) {
            return success(result);
          },
          error: function(result) {
            return fail(result);
          }
        });
      };

      Shared.prototype.fullDate = function(datetime) {
        var m;
        m = /^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)$/.exec(datetime);
        return m[3] + '/' + m[2] + '/' + m[1] + ' à ' + m[4] + ':' + m[5];
      };

      return Shared;

    })();
    return new Shared;
  });

}).call(this);
