// Generated by CoffeeScript 1.4.0
(function() {

  require(['Shared'], function(Shared) {
    Handlebars.registerHelper('fullDate', function(datetime) {
      var m;
      m = /^(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)$/.exec(datetime);
      return m[3] + '/' + m[2] + '/' + m[1] + ' à ' + m[4] + ':' + m[5];
    });
    return Shared.ApiMakeRequest('events/list.php', {
      id: 'e00001'
    }, function(result) {
      if (!(result.error != null)) {
        return require(['text!admin/events/eventsList.html'], function(eventsListTmpl) {
          var template;
          template = Handlebars.compile(eventsListTmpl);
          return $('.h_events_list').html(template({
            events: result
          }));
        });
      }
    });
  });

}).call(this);
