// Generated by CoffeeScript 1.4.0
(function() {

  require(['Shared'], function(Shared) {
    Handlebars.registerHelper('fullDate', function(datetime) {
      return Shared.fullDate(datetime);
    });
    return Shared.ApiMakeRequest('subscribers/list.php', {
      event_id: 'e00001',
      fields: 'id,email'
    }, function(result) {
      console.log(result);
      if (!(result.error != null)) {
        return require(['text!../../templates/admin/subscribers/subscribersList.html'], function(subscribersListTmpl) {
          var template;
          template = Handlebars.compile(subscribersListTmpl);
          return $('.h_subscribers_list').html(template({
            subscribers: result
          }));
        });
      }
    });
  });

}).call(this);
